apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-orchestrator
  labels:
    app: mock-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-orchestrator
  template:
    metadata:
      labels:
        app: mock-orchestrator
    spec:
      containers:
      - name: mock-orchestrator
        image: dhii-mail-mock-orchestrator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_ENV
          value: "development"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mock-orchestrator
spec:
  type: ClusterIP
  selector:
    app: mock-orchestrator
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP